name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@main
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci
      - name: run linter
        run: npm run lint
      - name: run tests
        run: npm test
      - name: upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.0
      - name: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish
